name: Update Copilot Context

on:
  push:
    paths:
      - 'specs/**'
      - 'tools/**'
  pull_request:
    paths:
      - 'specs/**'
      - 'tools/**'
  workflow_dispatch:

jobs:
  update-context:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Update Copilot context
        run: npm run update-context
        
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD -- context-for-copilot.js docs/copilot-quick-reference.md .github/instructions/copilot-instructions.md TODO.md; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add context-for-copilot.js docs/copilot-quick-reference.md .github/instructions/copilot-instructions.md TODO.md
          git commit -m "Auto-update Copilot context files"
          git push